on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [docker]
    types:
      - completed

name: Deploy to AWS ECS
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Branch
      run: echo ${{ github.event.workflow_run.head_branch }}
    - name: workflow
      run: echo ${{ github.event.workflow_run.repository.name }}
   