on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [docker]
    types:
      - completed

name: Deploy to AWS ECS
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Deploy
      run: echo "tests finished with status ${{github.event.workflow_run.conclusion}}"
    - name: Finish
      run: echo "End deploy with success with file on branch master"
