on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [docker]
    types:
      - completed

if: ${{github.ref != 'refs/heads/master'}}
env:
  RAILS_ENV: staging
  RAKE_ENV: staging
name: Deploy to AWS ECS
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Deploy
      run: echo "tests finished with status ${{github.event.workflow_run.conclusion}}"
      run: RAILS_ENV
      run: echo "-> ${{RAILS_ENV}} "
    - name: Finish
      run: echo "End deploy with success on branch docker"