on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [docker]
    types:
      - completed

name: Deploy to AWS ECS
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Set enviroment
      if: ${{github.ref != 'refs/heads/master'}}
      env:
        RAILS_ENV: staging
        RAKE_ENV: staging
      run: echo $RAILS_ENV
    - name: Deploy
      run: echo "tests finished with status ${{github.event.workflow_run.conclusion}}"
    - name: RAILS_ENV
      run: echo $RAILS_ENV
    - name: Finish
      run: echo "End deploy with success on branch docker"